version: "3.8"
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: timeseries
    volumes:
      - timeseries_db:/var/lib/postgresql/data
volumes:
  timeseries_db:

